- name: Deploy on EC2 (pull image & restart)
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER || 'ec2-user' }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: IMAGE_NAME
          script: |
            set -e
            cd "${{ env.APP_PATH }}"

            # Install Docker if not present
            if ! command -v docker >/dev/null 2>&1; then
              echo "Installing Docker..."
              sudo dnf update -y
              sudo dnf install -y docker
              sudo systemctl enable --now docker
              sudo usermod -aG docker $USER || true
              
              # Re-login to apply group changes
              newgrp docker || true
            fi

            # Install Docker Compose plugin if not present
            if ! docker compose version >/dev/null 2>&1; then
              echo "Installing Docker Compose plugin..."
              DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
              mkdir -p $DOCKER_CONFIG/cli-plugins
              curl -SL https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
              chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            fi

            echo "Using IMAGE_NAME: $IMAGE_NAME"
            docker compose version
            
            export TAG=latest
            docker compose pull
            docker compose up -d
            docker image prune -f
            docker compose ps