name: Build & Deploy MCP Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/mcp-crypto-portfolio
  APP_PATH: /home/ec2-user/mcp-crypto-portfolio

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        id: meta
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "tag=main-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.ref_name }}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || github.token }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ steps.meta.outputs.tag }} \
            -t $IMAGE_NAME:latest \
            .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${{ steps.meta.outputs.tag }}
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (needed for scp sources)
        uses: actions/checkout@v4

      - name: Setup SSH key file from secret
        id: sshkey
        shell: bash
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          set -e
          if [[ -z "$SSH_KEY" ]]; then
            echo "EC2_SSH_KEY is empty"; exit 1
          fi
          # Create SSH key in /tmp with proper permissions
          KEY_FILE="/tmp/id_ec2_$$"
          printf '%s\n' "$SSH_KEY" > "$KEY_FILE"
          chmod 600 "$KEY_FILE"
          ls -la "$KEY_FILE"
          echo "key_path=$KEY_FILE" >> "$GITHUB_OUTPUT"

      - name: Debug SSH key
        run: |
          echo "SSH key file location: ${{ steps.sshkey.outputs.key_path }}"
          ls -la "${{ steps.sshkey.outputs.key_path }}"
          head -n 1 "${{ steps.sshkey.outputs.key_path }}"
          tail -n 1 "${{ steps.sshkey.outputs.key_path }}"
          # Test SSH key format
          ssh-keygen -l -f "${{ steps.sshkey.outputs.key_path }}" || echo "Invalid SSH key format"

      - name: Validate workspace files
        run: |
          ls -la
          test -f docker-compose.yml || (echo "missing docker-compose.yml" && exit 1)
          test -f nginx.conf || (echo "missing nginx.conf" && exit 1)

      - name: Ensure target dir exists on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER || 'ec2-user' }}
          key_path: ${{ steps.sshkey.outputs.key_path }}
          port: 22
          script: |
            set -e
            mkdir -p "${{ env.APP_PATH }}"
            ls -la "${{ env.APP_PATH }}"

      - name: Upload compose & nginx.conf to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER || 'ec2-user' }}
          key_path: ${{ steps.sshkey.outputs.key_path }}
          port: 22
          source: "./docker-compose.yml,./nginx.conf"
          target: ${{ env.APP_PATH }}
          overwrite: true
          debug: true

      - name: Deploy on EC2 (pull image & restart)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER || 'ec2-user' }}
          key_path: ${{ steps.sshkey.outputs.key_path }}
          port: 22
          script: |
            set -e
            cd "${{ env.APP_PATH }}"

            if ! command -v docker >/dev/null 2>&1; then
              # Amazon Linux 2023
              sudo dnf update -y
              sudo dnf install -y docker docker-compose-plugin
              sudo systemctl enable --now docker
              sudo usermod -aG docker $USER || true
            fi

            echo "Deploying $IMAGE_NAME:latest"
            export TAG=latest
            docker compose pull
            docker compose up -d
            docker image prune -f
            docker compose ps